### ISSUE TITLE
How to block until UniTask completion within a synchronous method?

### ISSUE THREAD

**Issue by brmenchl** [Cysharp/UniTask#223]
I know that this runs counter to the point of using async in the first place, but there's a good reason. 

From within a Unity lifecycle event (e.g. Start). I need to call an async Unitask method (which is normally called async) and have it block until completion so that the rest of the lifecycle doesn't continue.

**Comment by KAW0** [comment]
Like that?
```
async UniTaskVoid Start()
{
        await AsyncMethod();
	/////Other stuff aftern AsyncMethod()

}
```

**Comment by brmenchl** [comment]
No sorry, it would have to be fully blocking, so not within an async UniTaskVoid method.

essentially, in editor during development, we need to make an http request before certain things initialize. Normally we do this asynchronously in another scene, but that prevents us from starting the editor from a scene thats not the first scene. I'd like to block main thread execution until this data is fetched so we don't need to put null checks in the code everywhere just for development.

**Comment by neuecc** [comment]
async method can not block.

I know what you want to do.
Let's create your own SceneManager to control the transitions.

```csharp
await SceneManager.NavigateAsync();
```

```csharp
interface IScene
{
    UniTask PrepareAsync(); // setup data from http request
    UniTask EnterAsync(); // entering process
    UniTask ExitAsync(); // disposing scene
}
```

**Comment by brmenchl** [comment]
wow this is great, thanks! So basically creating our own wrapper around scene transitions.

**Comment by drew-fc** [comment]
@neuecc @brmenchl , I am running into the exact same problem.
Would you please be able to expand a little and explain how you resolved this?
I have a scene that I want to test without loading my splash screen scene which loads the dependencies on the network first in the normal game.
The problem is, all my network dependencies are now UniTasks that run async.
How can I either force a UniTask to block, or achieve something similar? It seems like you figured this out, how can I do it without needing to load up a bootloader scene first? Or is the only way to use a bootloader scene?

**Comment by brmenchl** [comment]
Yeah essentially. We ended up not implementing anything, but we would have created a dev bootloader scene with a enum of the scene you want to start. Each enum value would correspond to a list of side effects and data (or mock data) that needs to be properly hydrated before the scene can load. Once those tasks are complete, the bootloader scene will automatically switch to the scene you want.
