### ISSUE TITLE
Disposing CancellationTokenSouce before CancellationTokenSouce.CancelAfterSlim triggers throws exception

### ISSUE THREAD

**Issue by Razenpok** [Cysharp/UniTask#242]
```csharp
private async UniTask FooAsync()
{
    var cts = new CancellationTokenSource();
    cts.CancelAfterSlim(3000);
    
    await DoSomeWorkAsync(cts.Token);

    cts.Dispose();
}
```

If `DoSomeWorkAsync` takes less than 3 seconds, then there will be a `ObjectDisposedException` thrown once 3 seconds passed. This behavior is different from `CancelAfter` which doesn't throw exceptions when the token source is disposed before timer trigger.

**Comment by neuecc** [comment]
CancelAfterSlim can not touch internal property, is disposed.
Make sure you call `Cancel` before `Dispose`.
```csharp
cts.Cancel();
cts.Dispose();
```
If you do so, the state can be detected via IsCancellationRequested, and no exception should be thrown.

I will also add the ability for CancelAfterSlim to return IDisposable so that the timer can be cancelled.

```csharp
using var cts = new CancellationTokenSource();
using cts.CancelAfterSlim(3000);

await DoSomeWorkAsync(cts.Token);
```

This would be the smartest way.

**Comment by neuecc** [comment]
`v2.2.4` released new API.
