### ISSUE TITLE
DLL for UniTask 

### ISSUE THREAD

**Issue by LudiKha** [Cysharp/UniTask#268]
Is there a version of UniTask available that's compiled to DLLs?

I'd like to use it throughout my projects so auto-referencing would be ideal. Using the editor-compiled DLLs fail during build mode, as there are references to UnityEditor in the runtime library.

Thanks!

**Comment by neuecc** [comment]
We are not going to provide a compiled dll (probably always a bad practice).
It would be ideal to completely separate Runtime from Editor, but due to some diagnostic features, it is not yet possible.
However, if you don't care about the diagnostic features, I think it is possible to generate the DLL itself, so I don't deny generating it myself.
