### ISSUE TITLE
Addressables Support

### ISSUE THREAD

**Issue by cg-adam** [Cysharp/UniTask#45]
Would be great to have support for the new addressables system, so we can attach progress handlers whilst we are awaiting the downloads etc.

**Comment by phongsoyenmoc** [comment]
You can refer to yKimisaki's LazyUnitask, how to use UniTaskCompletionSource to convert the loadable addressable work into a Unitask, you can see this link:
https://gist.github.com/yKimisaki/5f7d2846ba21fd9bfb5358de6e5f0ed8

I also forked again and added a few extension methods:
https://gist.github.com/phongsoyenmoc/211a9574a9b161a02c2fa553404c1600

**Comment by cg-adam** [comment]
Thanks, i'll take a look.

**Comment by garrafote** [comment]
+1 for this request.

I created a gist to work with AsyncOperationHandles directly as the new unity Localization package returns AsyncOperationHandles when retrieving localized table entries.

https://gist.github.com/garrafote/b3bcd6a27d163382d9647032ac1a1bfa

**Comment by neuecc** [comment]
Currently external package can not handle by #if symbol.
For this reason, please use your own extensions.

**Comment by randomPoison** [comment]
It would be possible to support this by creating a second package that provides the `AsyncOperationHandle`-specific extensions. That would make it so that only users using the Addressables packages would need to pull in the addressables-specific extensions.

It would be cool to have that included in the main repository as an official part of the UniTask project, but if @neuecc doesn't want to add that to UniTask then anyone could setup a separate package that provides these extensions 😁

**Comment by bdovaz** [comment]
@neuecc That's not true. Read "Version Defines" section:

https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by KAW0** [comment]
Maybe some class with "Uncomment to enable"?

**Comment by randomPoison** [comment]
@KAW0 that won't work when using UniTask as a Unity package. For package dependencies you can't modify their contents, so uncommenting a `#define` to enable addressable support wouldn't be an option. Also, modifying the source code of an external dependency is generally a bad practice (hence why packages are read-only by default), so that probably wouldn't be the right solution even if it were an option.

**Comment by garrafote** [comment]
cant you just define a custom symbol like #if UNITASK_ADDRESSABLE_SUPPORT and let people add this to their definitions? I've seen this being used on some unity's authored packages and it works ok and there is no need for extra packages. Don't get me wrong I still like UniTask but, sorry there is no excuse other than "I dont want to" or "it's out of our scope" not to add support to these packages and have users writing their own bloated copy-and-pasty and unverified extensions.

**Comment by randomPoison** [comment]
@garrafote You should absolutely make a pull request adding that functionality! It seems like @neuecc marked this as "won't fix" under the assumption that it couldn't be supported with UPM. If you provide the implementation you want, they'll probably be open to accepting it (though I could be wrong, I can't speak on their behalf).

**Comment by neuecc** [comment]
Thank you, I don't know soft-references and version-defines
https://blogs.unity3d.com/2019/04/16/introducing-unity-2019-1/#assembly
It works fine.

I've implements it for v2.
https://github.com/Cysharp/UniTask/blob/7f61f85bc74f50d7042caf64730d2ae85f34ff20/src/UniTask/Assets/Plugins/UniTask/External/AddressableAsyncExtensions.cs
The port to v1 is not currently being considered.
