### ISSUE TITLE
Is UniTask call order deterministic? In registration order?

### ISSUE THREAD

**Issue by perholmes** [Cysharp/UniTask#453]
The question is whether two UniTasks that are waiting for the same condition will be called in the same order they were registered.

Fictitious example. Two async functions both wait for a condition. Function #1 registers itself first.

Function #1:    await UniTask.WaitUntil(() => isActive == false);
Function #2:    await UniTask.WaitUntil(() => isActive == false);

When isActive becomes true, will function #1 always be the first to be called?

The only documentation I can find about this is that BeforeSceneLoad methods are called non-deterministically, which is about Unity infrastructure. But since it's the only mention of non-determinism, can I interpret that to mean that everything else is deterministic?

**Comment by Blackclaws** [comment]
> The question is whether two UniTasks that are waiting for the same condition will be called in the same order they were registered.

Yes, they should be. Let me give a code based answer instead of ChatGPT:
``` UniTask.WaitUntil(predicate) ``` uses ``` WaitUntilPromise ``` under the hood, which adds itself to the ```PlayerLoopTiming``` queue of your choosing, if you select none its ```PlayLoopTiming.Update```. They are added to an array in the order in which they were called and the array is iterated on every update loop to check whether the predicate has been fulfilled, in which case the continuation is called.

ChatGPT is by the way wrong that UniTask is implemented using coroutines. UniTask directly injects itself into the PlayerLoopSystem's various subsystems.

**Comment by perholmes** [comment]
Thanks, I appreciate it! Indeed, I was worried about relying on the implementation to get called back in order. The problem is that these are alert with states that can be changed while an alert is open, so I want to allow them to queue. I was hoping to avoid making a queue system. But maybe I should just make modeless notifications instead and let them all pop up.

Interesting that ChatGPT was so wrong and so confidently. We're using it for some text processing that it does remarkably well. But when it has to be precise, I'm afraid of trusting it, and this confirms it.

**Comment by perholmes** [comment]
It's by design that I want the callbacks to be called. These are changes in activation state, and if it changes while the first alert is open, the second alert would pop up after it. The easy way to handle this rare occurrence would be to simply let each alert camp-on.

This goes through a modal system we have where only one potentially modal process can run at a time, so a sign-in flow doesn't get interrupted by an update check. But it's just one design option among many.

Realistically, is there any risk that UniTask would stop registering callbacks in an array? I'm wondering how many apps are unknowingly relying on the sequence being in the registered order and would misbehave if this were to change.

**Comment by Blackclaws** [comment]
> It's by design that I want the callbacks to be called. These are changes in activation state, and if it changes while the first alert is open, the second alert would pop up after it. The easy way to handle this rare occurrence would be to simply let each alert camp-on.
> 
> This goes through a modal system we have where only one potentially modal process can run at a time, so a sign-in flow doesn't get interrupted by an update check. But it's just one design option among many.
> 
> Realistically, is there any risk that UniTask would stop registering callbacks in an array? I'm wondering how many apps are unknowingly relying on the sequence being in the registered order and would misbehave if this were to change.

There is always risk that internals of a library might change. If this is behaviour you are relying on you should make sure on upgrading the library that its still the same way. 

It might make sense to just block in your modal system on a ```SemaphoreSlim``` or something similar to prevent concurrent access. That one doesn't guarantee the order in which dialogs will be shown but you can prevent multiple dialogs from being shown.

Anyway as long as your design works for you its fine, you should probably just add a comment to the relevant parts of code that documents that you are relying on internal library behaviour.

**Comment by yellowisher** [comment]
Actually the order **can be changed**. It stores callbacks in registration order, loops the array in that order. However, if any `IPlayerLoopItem` (callback) finishes, (or gets cancelled/throws an exception) the item is removed from the array (null is placed at that index).

In such case, to fill the null hole in the array, it find active item from the **tail** and sawp it. This changes the order of the items. It could preserve the order by pulling items beyond the null item, but I think it's by design which is faster.
https://github.com/Cysharp/UniTask/blob/f2773f585e762480c835ac718b82b87cb111e500/src/UniTask/Assets/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs#L168-L241

**Comment by neuecc** [comment]
Thanks for the reply with the source code.
You are correct, there is no guarantee of the callback sequence.
Think of it as the same way that there is no guaranteed loop order in Dictionary.
