### ISSUE TITLE
Android build failed with BuildOptions.AllowDebugging due to unityLibrary:BuildIl2CppTask

### ISSUE THREAD

**Issue by Just4F** [Cysharp/UniTask#471]
In the situation where importing the UniTask plugin without modifying any code, exporting an Android build using BuildOptions.AllowDebugging fails to build.
    However, if BuildOptions.AllowDebugging is not set, the build will succeed (With BuildOptions.Development
                                    | BuildOptions.EnableDeepProfilingSupport)
   
    The project includes several third-party plugins such as OxSdk, Firebase, FacebookSDK etc.. Making it extremely difficult to pinpoint which plugin is causing the failure.
    Any suggestions for this scenario ?
        
    Unity version: 2021.3 .11f 1.

    Error with BuildOptions.AllowDebugging:
    relocation truncated to fit: R_AARCH64_CALL26 against symbol __clang_call_terminate' defined in .text.__clang_call_terminate[__clang_call_terminate] 
    Error with BuildOptions.ConnectWithProfiler: 
    relocation truncated to fit: R_AARCH64_CALL26 against symbol operator delete(void*)' defined in .text._ZdlPv section

**Comment by hadashiA** [comment]
There seems to be a lack of information :/
Perhaps Unity is successfully executing Il2cpp. Then it is failing to compile the native code.

You could try "Export Project." It generates a project and may give you more detailed build errors on Android Stdio.

Also, in my experience, it could be due to the large binary size.
The following forum may be helpful:
https://forum.unity.com/threads/android-builds-failing-when-script-debugging-is-enabled.1027357/

In any case, there seems to be a lack of evidence that this is a UniTask issue.
