### ISSUE TITLE
PlayerLoop Initialize vs Init

### ISSUE THREAD

**Issue by Merglasch** [Cysharp/UniTask#483]
The unitask player loop is normally initialized at BeforeSceneLoad. But as the readme says, there might be reasons to initialize it earlier. The suggested workflow for this is as follows:
![grafik](https://github.com/Cysharp/UniTask/assets/4222741/3e5cd045-2842-424b-b087-5986c6acb761)
But when looking at the unitask code, it uses PlayerLoopHelper.Init() to initialize instead of PlayerLoopHelper.Initialize.
Init calls Initialize, but also for example sets variables like unitySynchronizationContext, mainThreadId and applicationDataPath.

Following Questions come to mind:

- Is there a reason unitask doesn't just initialize earlier (e.g. at AfterAssembliesLoaded)?
- Why does part of the initialization happen in Init? Why not everything in Initialize? 
- It seems dangerous to only half-initialize unitask and use it, but that is what the readme recommends by calling PlayerLoopHelper.Initialize? For example unitySynchronizationContext is used to post exceptions, so that seems like something that should really be initialized?
- In the ECS case it is recommended to re-initialize unitask after ecs has initialized its player loop stuff, is there a callback/good time to do that?

**Comment by hadashiA** [comment]
Hi, I'm not the original author, but I got to hear the story, so I'll try to respond :)

> Is there a reason unitask doesn't just initialize earlier (e.g. at AfterAssembliesLoaded)?

The reason for using `BeforeSceneLoad` is because Unity 2018.4〜 is supported.
`AfterAssembliesLoaded` was added in Unity 2020.

> Why does part of the initialization happen in Init? Why not everything in Initialize?

Basically, we did not want to expose the entire UniTask initialization process to the user.
Only the process of setting the PlayerLoop needs to be allowed to be freely invoked. This is because we don't know when other libraries will set PlayerLoop. In `Initialize`, only the part where the user can freely specify the timing is cut out.

> It seems dangerous to only half-initialize unitask and use it, but that is what the readme recommends by calling PlayerLoopHelper.Initialize? For example unitySynchronizationContext is used to post exceptions, so that seems like something that should really be initialized?
> In the ECS case it is recommended to re-initialize unitask after ecs has initialized its player loop stuff, is there a callback/good time to do that?

`PlayerLoop.Initialize()` is allowed to be called early. It is also allowed to be called multiple times.

However, even if we do so, we can only start using UniTask at the BeforeSceneLoad timing. 
Currently, there is no way to change this, but perhaps that won't be a problem?

If you really need to do that, please start a separate issue with sample code.
Thanks!

**Comment by Merglasch** [comment]
Thank you for the answer @hadashiA 

Just for clarification, so I don't run off into a wrong direction.

The only reason for Unitask to initialize as late as BeforeSceneLoad is compatibility with Unity 2018/2019?

Calling PlayerLoop.Initialize earlier than BeforeSceneLoad doesn't actually let me use Unitask earlier, since it is not fully initialized at that point?

If those two are the case, I will probably start an issue/pull request to change the time of that Init call from BeforeSceneLoad to AfterAssembliesLoaded for Unity Versions 2020 and higher. This would allow using unitask at BeforeSceneLoad time, which is currently not possible since order between multiple BeforeSceneLoad calls is not defined.

**Comment by hadashiA** [comment]
> The only reason for Unitask to initialize as late as BeforeSceneLoad is compatibility with Unity 2018/2019?

Perhaps the major reason is this.

Also, I have yet to figure out a use case where we want to use UniTask before BeforeSceneLoad.
It would be helpful if you could show me the use case.
PR is welcome. Thanks.
