### ISSUE TITLE
Version 2.4.0: exception when load scene async

### ISSUE THREAD

**Issue by laicasaane** [Cysharp/UniTask#504]
Unity 2022.3.8f1

This code works fine with UniTask 2.3.3 but throws exception for 2.4.0. The changelog mentions breaking changes however I don't know if they relate to this issue?

```cs
await SceneManager.LoadSceneAsync(buildIndex, LoadSceneMode.Additive)
    .ToUniTask(cancellationToken: cancelToken);
```

```
ArgumentNullException: Value cannot be null.
Parameter name: asyncOperation
—
System.ArgumentNullException: Value cannot be null.
Parameter name: asyncOperation
void Cysharp.Threading.Tasks.Internal.Error.ThrowArgumentNullExceptionCore(string paramName) in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/Internal/Error.cs:20
UniTask Cysharp.Threading.Tasks.UnityAsyncExtensions.ToUniTask(AsyncOperation asyncOperation, IProgress<float> progress, PlayerLoopTiming timing, CancellationToken cancellationToken) in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/UnityAsyncExtensions.cs:35
async UniTaskVoid Module.Worlds.MainWorld.LoadDebugSceneBehaviour.Load(CancelToken cancelToken) in Assets/Modules/Module.Worlds.MainWorld/Modules/LoadDebugSceneBehaviour.cs:31
—
at void UnityEngine.DebugLogHandler.Internal_LogException(Exception, Object)
void UnityEngine.DebugLogHandler.LogException(Exception exception, Object context)
void UnityEngine.Logger.LogException(Exception exception, Object context)
void UnityEngine.Debug.LogException(Exception exception)
void Cysharp.Threading.Tasks.UniTaskScheduler.PublishUnobservedTaskException(Exception ex) in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/UniTaskScheduler.cs:90
async UniTaskVoid Module.Worlds.MainWorld.LoadDebugSceneBehaviour.Load(CancelToken cancelToken) in Assets/Modules/Module.Worlds.MainWorld/Modules/LoadDebugSceneBehaviour.cs:31
bool Cysharp.Threading.Tasks.UniTaskCompletionSourceCore<object>.TrySetResult(object result) in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/UniTaskCompletionSource.cs:139
bool Cysharp.Threading.Tasks.UniTask+WaitUntilPromise.MoveNext() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/UniTask.WaitUntil.cs:129
void Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/Internal/PlayerLoopRunner.cs:203
void Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.Update() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/Internal/PlayerLoopRunner.cs:145
void Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.Run() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/Internal/PlayerLoopRunner.cs:104
void Cysharp.Threading.Tasks.PlayerLoopHelper.ForceEditorPlayerLoopUpdate() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/PlayerLoopHelper.cs:360
void UnityEditor.EditorApplication.Internal_CallUpdateFunctions()
```

**Comment by hadashiA** [comment]
Hello. The following snippet itself seems to work fine in 2.4.0.

```csharp
await SceneManager.LoadSceneAsync(buildIndex, LoadSceneMode.Additive)
    .ToUniTask(cancellationToken: cancelToken);
```

I would like information on when this code was executed.

But according to the stack trace, this is not Play Mode, is it?

> void Cysharp.Threading.Tasks.PlayerLoopHelper.ForceEditorPlayerLoopUpdate() in ./Library/PackageCache/com.cysharp.unitask@2.4.0/Runtime/PlayerLoopHelper.cs:360

If so, LoadSceneAsync would not work properly.

**Comment by laicasaane** [comment]
> But according to the stack trace, this is not Play Mode, is it?

No, this exception happens in Play Mode. After the main scene is fully loaded, I run this code to load other scenes as you can see here:

```cs
private async UniTaskVoid Load(CancelToken cancelToken)
{
    var taskEntities = LoadSceneAsync<MainSceneEntitiesReadyTag>(SceneKind.MainScene_Entities, cancelToken);
    var taskMono = LoadSceneAsync<MainSceneMonoReadyTag>(SceneKind.MainScene_Mono, cancelToken);
    var taskUI = LoadSceneAsync<MainSceneUIReadyTag>(SceneKind.MainScene_UI, cancelToken);

    await UniTask.WhenAll(taskEntities, taskMono, taskUI);
}

private async UniTask LoadSceneAsync<T>(SceneKind kind, CancelToken cancelToken)
    where T : unmanaged, IComponentData
{
    await UniTask.WaitUntil(static () => WorldSceneBuild.IsReady);

    var id = kind.ToId();

    if (WorldSceneBuild.TryGetSceneBuildIndex(id, out var index) == false)
    {
        Unity.Logging.Log.Error($"Cannot find {kind}");
        return;
    }

    await SceneManager.LoadSceneAsync(index, LoadSceneMode.Additive)
        .WithCancellation(cancelToken);

    LatiosWorld.worldBlackboardEntity.AddComponent<T>();
}
```

But my Play Mode Settings are like this, could that be the cause?
![image](https://github.com/Cysharp/UniTask/assets/1594982/2290032a-2b9e-4441-9aff-53f226e312db)

**Comment by hadashiA** [comment]
@laicasaane  

I used UniTask.WhenAll and checked it with code as close to your snippet as possible and it worked fine.

The error you present is a null reference to asyncOperation, which is probably only possible if `LoadSceneAsync` itself returns null, or if AsyncOperation is Destroyed.

By the way, since `.WithCancellation` fails immediately, is it possible that the index of the first argument of `LoadSceneAsync` is a non-existent number?  Check to see if `LoadSceneAsync` alone succeeds.

UniTask v2.4.0 has a change in the way WhenAll exceptions are reported, but it is a change in whether the exception is Aggregated or not.

**Comment by laicasaane** [comment]
I've found the cause https://github.com/Cysharp/UniTask/commit/7c62904a74eb6f085619b5ff8f10a6d77c13bfe0

Revert this commit and UniTask 2.4.0 works again without problem.

**Comment by hadashiA** [comment]
Interesting. However, since I cannot reproduce it, so I cannot determine why `AfterAssembliesLoaded` causes the problem.

Sorry, but I have a few more questions.

1. How is the `async UniTaskVoid Load()` started?  Is it using `Awake` or `Start` of the `main scene` GameObject? Or is it started by some other trigger?
    - Note:
      - It is strange that the stack trace shows ForceEditorPlayerLoopUpdate.
      - I've investigated, it seems that AfterAssembliesLoaded is called in Edit mode as well, since it is called on successful compilation. I suspect this is triggering something in your application.
2. For some reason, `LoadSceneAsync()` must be returning null, but `LoadSceneAsync` itself is not emit any other log records? (Because I don't know of any case where it returns null without spitting out additional logs.)

**Comment by laicasaane** [comment]
1. It's started by `Awake` of a gameobject in the main scene.
2. `LoadSceneAsync` does not emit any log. The log I show you is the only one in the Console window.

**Comment by hadashiA** [comment]
Thanks for the information.

📝 I have not yet fully understood the impact of AfterAssembliesLoaded, but I was able to get a fairly close error by doing the following:

```csharp
    async UniTaskVoid Awake()
    {
        await UniTask.WaitUntil(() => !EditorApplication.isPlaying);
        await SceneManager.LoadSceneAsync(1, LoadSceneMode.Additive);
    }
```

Play -> (wait secs) -> Exit ,  so get a similar ArgumentException (by PublishUnobservedTaskException) without any other log records.

```
ArgumentNullException: Value cannot be null.
Parameter name: asyncOperation
Cysharp.Threading.Tasks.Internal.Error.ThrowArgumentNullExceptionCore (System.String paramName) (at Assets/Plugins/UniTask/Runtime/Internal/Error.cs:20)
Cysharp.Threading.Tasks.Internal.Error.ThrowArgumentNullException[T] (T value, System.String paramName) (at Assets/Plugins/UniTask/Runtime/Internal/Error.cs:14)
Cysharp.Threading.Tasks.UnityAsyncExtensions.GetAwaiter (UnityEngine.AsyncOperation asyncOperation) (at Assets/Plugins/UniTask/Runtime/UnityAsyncExtensions.cs:23)
Hoge.Awake () (at Assets/Scripts/Hoge.cs:23)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/Plugins/UniTask/Runtime/UniTaskScheduler.cs:90)
```

- WaitUntil started in Play mode will continue to run in Edit mode.
- LoadSceneAsync called in Edit Mode returns null. Boom!
    - Strangely, no error is reported; it just returns null. (It should really be "This can only be used during play mode," or something like that.)

I don't know if your problem is exactly the same, but it would be similar to a large extent.
 I would like to know when the error occurs.

This occurs when the "Enter Play Mode Option" is turned on. However, once the problem occurs, it continues to occur even if the option is turned off.
If the compilation is run once after turning it off, the problem will not occur.

For now, in my investigation, I have not found any evidence that `AfterAssembliesLoaded` has anything to do with it, because the behavior changes when I re-compile something.

**Comment by laicasaane** [comment]
The error occurs even "Enter Play Mode Options" is turned off. It also occurs even after a recompilation.

**Comment by laicasaane** [comment]
I've found the problem. It doesn't relate to UniTask at all. Actually the cause is a flaw in my bootstrap that sets up the entire ECS system hierarchy. My apologies for causing you this much trouble.
