### ISSUE TITLE
Impossible to use with UnityAction

### ISSUE THREAD

**Issue by OmiCron07** [Cysharp/UniTask#563]
There are two problems with UniTask and UnityAction.

First, `UniTask.UnityAction()` does not take the parameter of `UnityAction<T>`. Second, when calling the `UnityAction<T>`, it is impossible to block the call to be able to add code after the event because of the `fire and forget` wrapping of the `UniTask.UnityAction()`. 

Is there a way to convert an async call to sync ? Because `.GetAwaiter().GetResult()` does not work and it should.

**Comment by neuecc** [comment]
Asynchronous calls cannot be converted to synchronous calls.
The architecture of the application must be redesigned.
Fundamentally, the framework itself needs to support async (e.g. something like UnityAsyncAction ......).
Since Awaitable was added in Unity 6, it will be promoted to make the framework support async/await.
