### ISSUE TITLE
AutoResetUniTaskCompletionSource cannot be awaited by multiple targets

### ISSUE THREAD

**Issue by jarrodspurrier** [Cysharp/UniTask#582]
I get the following error whenever I try to have more than one class await the same AutoResetUniTaskCompletionSource: `InvalidOperationException: Already continuation registered, can not await twice or get Status after await.`. In the following code I simply call `InitializedCompletionSource.TrySetResult()` when Initialized is set to true.
   
```csharp
public UniTask WaitUntilInitialized()
{
    if (Initialized)
    {
        return UniTask.CompletedTask;
    }

    InitializedCompletionSource ??= AutoResetUniTaskCompletionSource.Create();

    return InitializedCompletionSource.Task;
}
```
As soon as I switch it back to it being a UniTaskCompletionSource, it works as expected and both class's can await it.

**Comment by neuecc** [comment]
Yes, AutoReset responds to await and automatically resets, so it does not support multiple times.
If you want to create a TaskCompletionSource that suppresses allocation, you can create one that resets manually (using UniTaskCompletionSourceCore).
However, since it becomes an API where the user needs to explicitly call Reset, it may be difficult to make it work well.

**Comment by jarrodspurrier** [comment]
So I revisited this in attempt to create a wrapper class around UniTaskCompletionSourceCore, but it appears it has the same limitation of not being able to await multiple times. What would be the suggested approach for being able to pool a UniTaskCompletionSource that supports multiple awaiters?
