### ISSUE TITLE
How to define UNITASK_DOTWEEN_SUPPORT if I'm using UniTask from NuGet?

### ISSUE THREAD

**Issue by djnjbjb** [Cysharp/UniTask#609]
Defining UNITASK_DOTWEEN_SUPPORT is needed if I want to use UniTaks with Dotween.
But if I use UniTask From NuGet (by [NugetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)), I found that defining UNITASK_DOTWEEN_SUPPORT in Unity Project has no use. UniTask is already a DLL not source code.
How to define UNITASK_DOTWEEN_SUPPORT if I'm using UniTask from NuGet?

**Comment by franktmy** [comment]
![image](https://github.com/user-attachments/assets/9d01125d-2796-4235-b07b-542306e8fab0)

My solution is to define it this way.Hope it helps.

**Comment by djnjbjb** [comment]
> ![image](https://private-user-images.githubusercontent.com/168816603/361425583-9d01125d-2796-4235-b07b-542306e8fab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDcwNTksIm5iZiI6MTcyNTM0Njc1OSwicGF0aCI6Ii8xNjg4MTY2MDMvMzYxNDI1NTgzLTlkMDExMjVkLTI3OTYtNDIzNS1iMDdiLTU0MjMwNmU4ZmFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwNjU5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTQ4NzZiYmRhNGE1OTdmMGRiNDlhNmIyMmI3OTEzOTliZGYzYWFjNWFkZjg5MWM0OGM3YWZiMDFhMDBiYTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x0B73h2U2TLfYUpmDMc4TgZgAEgGJarQdp7ACZnE8vw)
> 
> My solution is to define it this way.Hope it helps.

Not works for me.   
I'm using a [match-3 SDK](https://github.com/LibraStack/Match3-SDK) in my project. It uses UniTask. Several DoTween WithCancellation function calls in this SDK need UNITASK_DOTWEEN_SUPPORT.
If I use UniTask by source code and define UNITASK_DOTWEEN_SUPPORT. It works fine.
But if I use UniTask from NuGet. It not works. 
UNITASK_DOTWEEN_SUPPORT not works.
DEV not works either.

**Comment by laicasaane** [comment]
Compilation symbols only work for source code. Currently Nuget only distribute prebuilt dlls, so it won't work. When building the library, the compiler has already process the symbols and exclude the code from the final dlls.

You can add additional features to your project by installing companion dlls. However, atm there is no prebuilt dll for Addressables, TextMeshPro, DOTween extensions for UniTask. We can technically make a custom build pipeline for them. But we can't legally distribute them on Nuget. It has been expressed clearly by a Unity employee that anything references Unity Editor or Unity Engine APIs can't be distributed on Nuget[^1][^2][^3]. Since Cysharp is a legal entity, they might want to avoid any potential legal dispute with Unity.

So your best option would be using the source code version instead of prebuilt dlls, if you want Unity-related functionalities.

[^1]: https://discussions.unity.com/t/unity-future-net-development-status/836646/2699
[^2]: https://discussions.unity.com/t/unity-future-net-development-status/836646/2701
[^3]: https://unity.com/legal/terms-of-service/software/package-guidelines

**Comment by laicasaane** [comment]
Compilation symbols only work for source code. Currently Nuget only distribute prebuilt dlls, so it won't work. When building the library, the compiler has already processed the symbols to exclude unreachable code from the final dlls.

You can add additional features to your project by installing companion dlls. However, atm there is no prebuilt dll for UniTask extensions for Addressables, TextMeshPro, DOTween. We can technically make a custom build pipeline for them. But we can't legally distribute them on Nuget. It has been expressed clearly by a Unity employee that anything references Unity Editor or Unity Engine APIs can't be distributed on Nuget[^1][^2]. It is also stated in the Unity Package Guidelines[^3]. Since Cysharp is a legal entity, they might want to avoid any potential legal dispute with Unity.

So your best option would be using the source code version instead of prebuilt dlls, if you want Unity-related functionalities.

[^1]: https://discussions.unity.com/t/unity-future-net-development-status/836646/2699
[^2]: https://discussions.unity.com/t/unity-future-net-development-status/836646/2701
[^3]: https://unity.com/legal/terms-of-service/software/package-guidelines

**Comment by djnjbjb** [comment]
> Compilation symbols only work for source code. Currently Nuget only distribute prebuilt dlls, so it won't work. When building the library, the compiler has already processed the symbols to exclude unreachable code from the final dlls.
> 
> You can add additional features to your project by installing companion dlls. However, atm there is no prebuilt dll for UniTask extensions for Addressables, TextMeshPro, DOTween. We can technically make a custom build pipeline for them. But we can't legally distribute them on Nuget. It has been expressed clearly by a Unity employee that anything references Unity Editor or Unity Engine APIs can't be distributed on Nuget[1](#user-content-fn-1-9b24b943f69fb1aab8d8c384246d83b4)[2](#user-content-fn-2-9b24b943f69fb1aab8d8c384246d83b4). It is also stated in the Unity Package Guidelines[3](#user-content-fn-3-9b24b943f69fb1aab8d8c384246d83b4). Since Cysharp is a legal entity, they might want to avoid any potential legal dispute with Unity.
> 
> So your best option would be using the source code version instead of prebuilt dlls, if you want Unity-related functionalities.
> 
> ## Footnotes
> 1. https://discussions.unity.com/t/unity-future-net-development-status/836646/2699 [↩](#user-content-fnref-1-9b24b943f69fb1aab8d8c384246d83b4)
> 2. https://discussions.unity.com/t/unity-future-net-development-status/836646/2701 [↩](#user-content-fnref-2-9b24b943f69fb1aab8d8c384246d83b4)
> 3. https://unity.com/legal/terms-of-service/software/package-guidelines [↩](#user-content-fnref-3-9b24b943f69fb1aab8d8c384246d83b4)

Thanks a lot. Very well explained.

There are details that I can not comprehend clearly now. I will dive into them later myself.
Besides, ↩ symbol for links looks very nice.

**Comment by laicasaane** [comment]
FYI, footnotes are automatically formatted by [GitHub Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes).

**Comment by laicasaane** [comment]
In case you don't know, there is another option to install Unity packages: OpenUPM. It automates the workload of installing a package and its dependencies into a Untity project. However OpenUPM only allows open sourced packages, and it can't provide ability to browse packages inside Unity Editor. Besides these 2 limitations, it's very good thing to exist and has helped us alot.

**Comment by djnjbjb** [comment]
> In case you don't know, there is another option to install Unity packages: OpenUPM. It automates the workload of installing a package along with its dependencies into a Untity project. However OpenUPM only allows open source packages, and it can't provide ability to browse packages inside Unity Editor. Besides these 2 limitations, it's very good thing to exist and has helped us alot.

Thanks, I will try OpenUPM.

I know OpenUPM about 1 or 2 years ago and tried it in one of my project.
Most Unity packages can be installed by "xxx.unitypackage" or by "add package ..." in Unity PackageManager. And Many packages are not included in OpenUPM at that time. So I gave up OpenUPM then.
But now it seems a lot packages are included in UpenUPM. It is a useful tool now, I should pick it up.
