### ISSUE TITLE
[Question] Why does the TaskPool not need to increment size via Interlocked?

### ISSUE THREAD

**Issue by doubleday** [Cysharp/UniTask#626]
The TaskPool is using `Interlocked.CompareExchange` as a synch gate for the intrusive pooled objects.

While I don't really know when we would have the case where such a pool request would come from another another thread (I assume it could happen when mixing ThreadPool tasks with UniTask?) I do not understand why the `size` counter can be incremented without using `Interlocked`?

What guarantees cache coherence? Couldn't two threads work on different local cached values of `size`?

I would have thought that i.e. here: https://github.com/Cysharp/UniTask/blob/master/src/UniTask/Assets/Plugins/UniTask/Runtime/TaskPool.cs#L111

we would need to use:

```c#
Interlocked.Increment(ref _size);

// instead of
_size++;
```

**Comment by timcassell** [comment]
The `if (Interlocked.CompareExchange(ref gate, 1, 0) == 0)` and `Volatile.Write(ref gate, 0);` act as a locking mechanism. It's very similar to a SpinLock, but without the spin. The increment is inside the protected region.

**Comment by doubleday** [comment]
Thinks Tim!


I'm actually aware of that. But there is a difference between the lock guarantees and cache coherence. The spin lock on the gate var does not necessarily mean that the unrelated var size is not cached on another CPU. 

Using Interlocked.Increment would create the cache coherence guarantee imo

**Comment by timcassell** [comment]
The first `Interlocked.CompareExchange` contains an implicit full memory barrier, so anything that comes after it will not be moved before it. The `Volatile.Write` which exits the lock contains a write barrier, so anything that came before it will not be moved after it, and the written value will be flushed to main memory. Everything in between those 2 operations is protected concurrency. It doesn't matter if any of those values are cached on another CPU, they will be re-fetched from main memory due to the full memory barrier implicit to the `Interlocked.CompareExchange`.

If any of those values were to be updated in another function without the `Interlocked.CompareExchange(ref gate, 1, 0)`, then it would be a race condition. But they are not, and everything is properly protected.

**Comment by neuecc** [comment]
Tim's insight is appropriate, thank you.
To add one point, the code here doesn't implement strict management.
In case of conflicts, cache misses may occur.
However, given the nature of pooling, this is considered acceptable (it's better to have additional allocations in the worst case than to always pay the cost of locking).

**Comment by doubleday** [comment]
Thanks a lot for the explanation @timcassell. Much appreciated. 

The thing that tripped me off I guess was the `Volatile.Write`. I thought I understood the memory ordering part of the barrier but I was simply wrong about that it would also flush the other variables.

**Comment by timcassell** [comment]
Technically, in .Net, writes to fields are always flushed to main memory. Volatile just guarantees that they are not re-ordered. https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md

**Comment by doubleday** [comment]
Thanks again for taking the time @timcassell. This was the proverbial missing link. I believe I got it now.
