### ISSUE TITLE
Addressables and AsyncOperationHandle

### ISSUE THREAD

**Issue by Nyankoo** [Cysharp/UniTask#91]
How do I get the `AsyncOperationHandle` in the current build? I'm doing the following:

`TextAsset myAsset = await Addressables.LoadAssetAsync<TextAsset>("myAssetLabel");`

This actually skips the step of getting the `AsyncOperationHandle`, which is needed when you want to call `Addressables.Release(asyncOperationHandle);` later.

**Comment by neuecc** [comment]
The timing of calling `Addressables.Release` may be soon after loading, or iit might be later.
So await can't make that decision, only load.

**Comment by GainDeveloper** [comment]
I'd recommend doing the following instead,

AsyncOperationHandle<TextAsset> loadHandle = Addressables.LoadAssetAsync("myAssetLabel");
await loadHandle.Task;

**Comment by neuecc** [comment]
`AsyncOperationHandle.Task` implementation is very poor.

```csharp
internal System.Threading.Tasks.Task<TObject> Task
{
    get
    {
        var handle = WaitHandle;
        return System.Threading.Tasks.Task.Factory.StartNew((Func<object, TObject>)(o =>
        {
            var asyncOperation = o as AsyncOperationBase<TObject>;
            if (asyncOperation == null) 
                return default(TObject);
            handle.WaitOne();
            return (TObject)asyncOperation.Result;
        }), this);
    }
}
```

I don't completely no recommend to use it.

**Comment by Nyankoo** [comment]
@neuecc And what would be your recommendation? Currently, awaiting `LoadAssetAsync `makes it impossible to call `Addressables.Release` later.

**Comment by neuecc** [comment]
```csharp
var handle = Addressables.LoadAssetAsync<TextAsset>("myAssetLabel");
var asset = await handle;
```

**Comment by GainDeveloper** [comment]
Since updating to latest UniTask & Addressables this doesn't seem to be possible anymore since 'await handle' returns a void type.

`            var handle = Addressables.LoadAssetAsync<TextAsset>("myAssetLabel");
            await handle;
            var result = handle.Result;`

This works but I assume is problematic since the task is pooled?
Any help would be appreciated.

**Comment by GainDeveloper** [comment]
I ended up doing this, though I assume it's less optimal than a proper implementation.

var handle = Addressables.LoadAssetAsync<UnityEngine.Object>(args.RefCounter.Resource);
await UniTask.WaitUntil(() => { return handle.IsDone; });

**Comment by neuecc** [comment]
still `LoadAssetAsync<T>` returns `AsyncOperationHandle<T>` and it can await result value.
(Addressables v1.16.15 - December 02, 2020).

**Comment by albertogomezr91** [comment]
This stills happens with Addressables v1.19.17 but only if your build settings are on Editor platform (Windows/Mac/Linux). If you switch to Android or iOS it works as expected.

Editor code:
`var locations = await Addressables.LoadResourceLocationsAsync(tag);`
`Cannot assign 'void' to an implicitly-typed local variable`

Android platform:
`var locations = await Addressables.LoadResourceLocationsAsync(tag);`
No error

**Comment by Merglasch** [comment]
@neuecc , @albertogomezr91 
This currently happens to me with Addressables 1.21.12

Both of these approaches
> var locations = await Addressables.LoadResourceLocationsAsync(tag);

> var handle = Addressables.LoadAssetAsync<TextAsset>("myAssetLabel");
var asset = await handle;

result in this error:
Cannot assign 'void' to an implicitly-typed local variable

The confusing thing is I can access the GetAwaiter and ToUnitask extensions on the handle, so I'd argue the UNITASK_ADDRESSABLE_SUPPORT define has to be active. Anything I am missing here?

**Comment by gibertoni** [comment]
I know this has been closed, but I have figured out why this error shows up in some projects.

The `await` is returning void because it is using the `EnumeratorAsyncExtensions` instead of the `AddressablesAsyncExtensions`. 
UniTask has defined in the asmdef to look for the `com.unity.addressable` resource and then define `UNITASK_ADDRESSABLE_SUPPORT`.

The code then has this `#if UNITASK_ADDRESSABLE_SUPPORT` on the Addressables.AsyncExtensions.cs

So, simply make sure to add `UniTask.Addressables` to your assembly definition reference list. It may not do automatically for you if it thinks that the EnumeratorAsyncExtensions suffices
